// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gqlgen-ent-combo/ent/schema"
	"gqlgen-ent-combo/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescText is the schema descriptor for text field.
	userDescText := userFields[0].Descriptor()
	// user.TextValidator is a validator for the "text" field. It is called by the builders before save.
	user.TextValidator = userDescText.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescPriority is the schema descriptor for priority field.
	userDescPriority := userFields[3].Descriptor()
	// user.DefaultPriority holds the default value on creation for the priority field.
	user.DefaultPriority = userDescPriority.Default.(int)
}
